imports:
    - { resource: 'maintenance.yml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Elements\Bundle\ProcessManagerBundle\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('ElementsProcessManagerBundle')"

    # auto-register all commands as services
    Elements\Bundle\ProcessManagerBundle\Command\:
        resource: '../../Command'

    Elements\Bundle\ProcessManagerBundle\SystemEventsListener: ~
