imports:
    - { resource: 'maintenance.yml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # auto-register all commands as services
    Elements\Bundle\ProcessManagerBundle\Command\:
        resource: '../../Command'

    Elements\Bundle\ProcessManagerBundle\SystemEventsListener: ~
